# coding: utf-8

"""
    Connect

    Connect is the best software for distributing your tickets to where your customers already are.  # noqa: E501

    OpenAPI spec version: v1
    Contact: dev@showpass.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import showpass_connect
from api.organizations_api import OrganizationsApi  # noqa: E501
from showpass_connect.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_organizations_create(self):
        """Test case for organizations_create

        """
        pass

    def test_organizations_delete(self):
        """Test case for organizations_delete

        """
        pass

    def test_organizations_list(self):
        """Test case for organizations_list

        """
        pass

    def test_organizations_partial_update(self):
        """Test case for organizations_partial_update

        """
        pass

    def test_organizations_read(self):
        """Test case for organizations_read

        """
        pass

    def test_organizations_update(self):
        """Test case for organizations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
