# coding: utf-8

"""
    Connect

    Connect is the best software for distributing your tickets to where your customers already are.  # noqa: E501

    OpenAPI spec version: v1
    Contact: dev@showpass.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import showpass_connect
from api.events_api import EventsApi  # noqa: E501
from showpass_connect.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_events_create(self):
        """Test case for events_create

        """
        pass

    def test_events_delete(self):
        """Test case for events_delete

        """
        pass

    def test_events_expanded(self):
        """Test case for events_expanded

        """
        pass

    def test_events_list(self):
        """Test case for events_list

        """
        pass

    def test_events_partial_update(self):
        """Test case for events_partial_update

        """
        pass

    def test_events_read(self):
        """Test case for events_read

        """
        pass

    def test_events_update(self):
        """Test case for events_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
