# coding: utf-8

"""
    Connect

    Connect is the best software for distributing your tickets to where your customers already are.  # noqa: E501

    OpenAPI spec version: v1
    Contact: dev@showpass.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import showpass_connect
from models.inventory_partner_based_ticket_type import InventoryPartnerBasedTicketType  # noqa: E501
from showpass_connect.rest import ApiException


class TestInventoryPartnerBasedTicketType(unittest.TestCase):
    """InventoryPartnerBasedTicketType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInventoryPartnerBasedTicketType(self):
        """Test InventoryPartnerBasedTicketType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = showpass_connect.models.inventory_partner_based_ticket_type.InventoryPartnerBasedTicketType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
