# coding: utf-8

"""
    Connect

    Connect is the best software for distributing your tickets to where your customers already are.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dev@showpass.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import showpass_connect
from api.variants_api import VariantsApi  # noqa: E501
from showpass_connect.rest import ApiException


class TestVariantsApi(unittest.TestCase):
    """VariantsApi unit test stubs"""

    def setUp(self):
        self.api = api.variants_api.VariantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_variants_create(self):
        """Test case for variants_create

        """
        pass

    def test_variants_delete(self):
        """Test case for variants_delete

        """
        pass

    def test_variants_list(self):
        """Test case for variants_list

        """
        pass

    def test_variants_partial_update(self):
        """Test case for variants_partial_update

        """
        pass

    def test_variants_read(self):
        """Test case for variants_read

        """
        pass

    def test_variants_update(self):
        """Test case for variants_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
