# coding: utf-8

"""
    Connect

    Connect is the best software for distributing your tickets to where your customers already are.  # noqa: E501

    OpenAPI spec version: v1
    Contact: dev@showpass.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import showpass_connect
from api.ticket_types_api import TicketTypesApi  # noqa: E501
from showpass_connect.rest import ApiException


class TestTicketTypesApi(unittest.TestCase):
    """TicketTypesApi unit test stubs"""

    def setUp(self):
        self.api = api.ticket_types_api.TicketTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ticket_types_create(self):
        """Test case for ticket_types_create

        """
        pass

    def test_ticket_types_delete(self):
        """Test case for ticket_types_delete

        """
        pass

    def test_ticket_types_expanded(self):
        """Test case for ticket_types_expanded

        """
        pass

    def test_ticket_types_list(self):
        """Test case for ticket_types_list

        """
        pass

    def test_ticket_types_partial_update(self):
        """Test case for ticket_types_partial_update

        """
        pass

    def test_ticket_types_read(self):
        """Test case for ticket_types_read

        """
        pass

    def test_ticket_types_update(self):
        """Test case for ticket_types_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
